project:
    name: titanic-survival-project-with-ml-ops


deployments:
    - name: dev
      executor: celery
      image:
        name: quay.io/astronomer/astro-runtime:7.3.0
      env: dev
      volumes:
        - ./include:/usr/local/airflow/include


